// <auto-generated />
using System;
using EnergyTracker.DataAccess.DataContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnergyTracker.Migrations
{
    [DbContext(typeof(EnergyDbContext))]
    partial class EnergyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("EnergyTracker.Domain.Entities.EnergyReading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("KWh")
                        .HasColumnType("REAL");

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Product", "Timestamp")
                        .IsUnique();

                    b.ToTable("Readings");
                });

            modelBuilder.Entity("EnergyTracker.Domain.Entities.ProductPrice", b =>
                {
                    b.Property<string>("Product")
                        .HasColumnType("TEXT");

                    b.Property<double>("PricePerKWh")
                        .HasColumnType("REAL");

                    b.HasKey("Product");

                    b.ToTable("ProductPrices");

                    b.HasData(
                        new
                        {
                            Product = "electricity",
                            PricePerKWh = 0.29999999999999999
                        },
                        new
                        {
                            Product = "gas",
                            PricePerKWh = 0.20000000000000001
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
